// Source of the portal's service worker.
//
// The portal is a static export on GitHub Pages, so there is no build step that
// could produce a precache manifest of hashed asset names. This worker is
// therefore runtime-cache only: it caches what a visitor actually fetches. That
// is the honest design for this deployment -- it makes the site installable and
// usable offline without pretending to know the asset graph ahead of time.
//
// The version string is stamped at export time (see export-github-pages.mjs) so
// that every published artifact gets its own cache namespace and the previous
// one is deleted on activation. A stale cache can therefore never outlive a
// deploy.

// The banner names the deployment that generated the file. This module is
// imported by tests that have no repository configuration to hand, so the
// organisation name is a parameter with a neutral default rather than a
// top-level import of project42.config.json; the exporter passes the configured
// name (see export-github-pages.mjs).
export function serviceWorkerSource(version, organizationName = "Project 42") {
  if (typeof version !== "string" || !/^[A-Za-z0-9._-]{1,64}$/.test(version)) {
    throw new Error(`Unusable service-worker version: ${version}`);
  }
  const bannerName =
    typeof organizationName === "string" && organizationName.trim().length > 0
      ? organizationName.trim().replace(/\*\//g, "")
      : "Project 42";

  return `/* ${bannerName} service worker -- generated by scripts/service-worker.mjs.
 * Do not edit the published copy; edit the source and re-export.
 */
const VERSION = ${JSON.stringify(version)};
const RUNTIME = "p42-runtime-" + VERSION;
const OFFLINE_URL = "/offline/";

/* Never cached, at any freshness. These carry or gate a signed-in session, and
 * a cached copy of one is worse than no copy at all: it can show one person's
 * state to the next, or resurrect a session the user has ended. Sign-in
 * correctness beats offline coverage every time. */
const NEVER_CACHE = [
  "/auth/",
  "/account",
  "/profile",
  "/learner-data",
  "/import-progress",
  "/transfer-progress",
  "/admin",
];

/* Content-addressed or deploy-locked: the bytes at these paths only change when
 * the path changes, so serving them from cache first is safe and is what makes
 * a repeat visit instant. */
const CACHE_FIRST = ["/themes/", "/layouts/", "/brand/", "/diagrams/", "/_next/static/"];

function isNeverCached(url) {
  return NEVER_CACHE.some(
    (prefix) => url.pathname === prefix || url.pathname.startsWith(prefix),
  );
}

function isCacheFirst(url) {
  return CACHE_FIRST.some((prefix) => url.pathname.startsWith(prefix));
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(RUNTIME).then((cache) => cache.add(OFFLINE_URL)).then(
      () => self.skipWaiting(),
      /* A missing offline page must not brick installation. */
      () => self.skipWaiting(),
    ),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== RUNTIME).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);

  /* Cross-origin is left entirely alone. In particular the account API origin
   * carries the session and must never be intercepted here. */
  if (url.origin !== self.location.origin) return;
  if (isNeverCached(url)) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(RUNTIME).then((cache) => cache.put(request, copy)).catch(() => {});
          return response;
        })
        .catch(() =>
          caches
            .match(request)
            .then((cached) => cached || caches.match(OFFLINE_URL))
            .then((cached) => cached || Response.error()),
        ),
    );
    return;
  }

  if (isCacheFirst(url)) {
    event.respondWith(
      caches.match(request).then(
        (cached) =>
          cached ||
          fetch(request).then((response) => {
            if (response.ok) {
              const copy = response.clone();
              caches.open(RUNTIME).then((cache) => cache.put(request, copy)).catch(() => {});
            }
            return response;
          }),
      ),
    );
    return;
  }

  /* Everything else: serve the cached copy immediately if there is one, and
   * refresh it in the background. */
  event.respondWith(
    caches.match(request).then((cached) => {
      const network = fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(RUNTIME).then((cache) => cache.put(request, copy)).catch(() => {});
          }
          return response;
        })
        .catch(() => cached || Response.error());
      return cached || network;
    }),
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "p42-skip-waiting") self.skipWaiting();
});
`;
}
