const ROOT_KEYS = new Set(['schemaVersion','unit','windowStart','windowEnd','identity','records']);
const IDENTITY_KEYS = new Set(['service','modelId','modelDigest','runtime','runtimeVersion','configDigest','releaseId']);
const RECORD_KEYS = new Set(['replicaId','buckets']);
const BUCKET_KEYS = new Set(['le','count']);
function object(value,name){if(value===null||typeof value!=='object'||Array.isArray(value))throw new Error(`${name} must be an object`)}
function exactKeys(value,allowed,name){for(const key of Object.keys(value))if(!allowed.has(key))throw new Error(`${name} has unknown field ${key}`);for(const key of allowed)if(!(key in value))throw new Error(`${name} is missing ${key}`)}
function text(value,name,max=200){if(typeof value!=='string'||value.length<1||value.length>max)throw new Error(`${name} must be a non-empty bounded string`)}
function instant(value,name){text(value,name,40);const time=Date.parse(value);if(!Number.isFinite(time)||new Date(time).toISOString()!==value)throw new Error(`${name} must be canonical ISO-8601 UTC`);return time}
export function validateFixture(input){object(input,'fixture');exactKeys(input,ROOT_KEYS,'fixture');if(input.schemaVersion!=='histogram-fixture/v1')throw new Error('unsupported schemaVersion');if(input.unit!=='ms')throw new Error('unsupported unit');const start=instant(input.windowStart,'windowStart');const end=instant(input.windowEnd,'windowEnd');if(end<=start||end-start>3600000)throw new Error('window must be positive and at most one hour');object(input.identity,'identity');exactKeys(input.identity,IDENTITY_KEYS,'identity');for(const key of IDENTITY_KEYS)text(input.identity[key],`identity.${key}`);if(!/^sha256:[0-9a-f]{64}$/.test(input.identity.modelDigest))throw new Error('invalid modelDigest');if(!/^sha256:[0-9a-f]{64}$/.test(input.identity.configDigest))throw new Error('invalid configDigest');if(!Array.isArray(input.records)||input.records.length<1||input.records.length>100)throw new Error('records must contain 1 through 100 replicas');const ids=new Set();let expectedBounds;for(const [ri,record] of input.records.entries()){object(record,`records[${ri}]`);exactKeys(record,RECORD_KEYS,`records[${ri}]`);text(record.replicaId,`records[${ri}].replicaId`,80);if(ids.has(record.replicaId))throw new Error('duplicate replicaId');ids.add(record.replicaId);if(!Array.isArray(record.buckets)||record.buckets.length<1||record.buckets.length>100)throw new Error('each record needs 1 through 100 buckets');let previousBound=0;let previousCount=0;const bounds=[];for(const [bi,bucket] of record.buckets.entries()){object(bucket,`bucket ${bi}`);exactKeys(bucket,BUCKET_KEYS,`bucket ${bi}`);if(!Number.isFinite(bucket.le)||bucket.le<=previousBound||bucket.le>3600000)throw new Error('bucket bounds must be finite, increasing, positive, and at most 3600000');if(!Number.isSafeInteger(bucket.count)||bucket.count<previousCount||bucket.count>1000000000)throw new Error('bucket counts must be safe, cumulative, nonnegative, and bounded');previousBound=bucket.le;previousCount=bucket.count;bounds.push(bucket.le)}if(previousCount<1)throw new Error('each replica must contain traffic');const key=JSON.stringify(bounds);if(expectedBounds===undefined)expectedBounds=key;else if(expectedBounds!==key)throw new Error('incompatible bucket bounds')}return input}
export function estimatePercentile(buckets,q){if(!Number.isFinite(q)||q<=0||q>1)throw new Error('quantile must be finite and in (0,1]');const total=buckets.at(-1).count;if(!Number.isSafeInteger(total)||total<1)throw new Error('histogram total must be positive');const rank=q*total;let previousCount=0;let previousBound=0;for(const bucket of buckets){if(rank<=bucket.count){const inBucket=bucket.count-previousCount;if(inBucket===0)return bucket.le;return previousBound+((rank-previousCount)/inBucket)*(bucket.le-previousBound)}previousCount=bucket.count;previousBound=bucket.le}return buckets.at(-1).le}
