import {
  LearningEventEngine,
  LearningEventEngineError,
  type LearningEventAccess,
  type LearningEventStore,
} from "./learning-event-engine.js";
import {
  LEARNING_EVENT_CONTRACT_VERSION,
  type LearningCommand,
} from "./learning-events.js";

export interface LearningEventConformanceScope {
  installationId: string;
  learnerId: string;
  ownerId?: string;
  keyPrefix?: string;
}

export interface LearningEventConformanceReport {
  contractVersion: typeof LEARNING_EVENT_CONTRACT_VERSION;
  checks: string[];
  eventCountBeforeDeletion: number;
  deletedEventCount: number;
}

/**
 * Runs the public Project 42 learning-event adapter contract.
 *
 * The caller must provide an isolated installation/learner pair whose backing
 * user records already exist. The harness deletes the learning-event stream at
 * the end, but it never deletes the installation or learner.
 */
export async function runLearningEventStoreConformance(
  store: LearningEventStore,
  scope: LearningEventConformanceScope,
): Promise<LearningEventConformanceReport> {
  const prefix = scope.keyPrefix ?? "project42-conformance";
  const ownerId = scope.ownerId ?? `${prefix}-owner`;
  const checks: string[] = [];
  const learnerAccess: LearningEventAccess = {
    installationId: scope.installationId,
    actorType: "learner",
    actorUserId: scope.learnerId,
    permissions: [
      "learning:write:self",
      "learning:read:self",
      "learning:delete:self",
    ],
  };
  const ownerAccess: LearningEventAccess = {
    installationId: scope.installationId,
    actorType: "owner",
    actorUserId: ownerId,
    permissions: [
      "learning:write:any",
      "learning:read:any",
      "learning:delete:any",
    ],
  };
  const engine = new LearningEventEngine(store, {
    now: () => "2026-07-28T13:00:00.000Z",
  });
  const command = (
    type: LearningCommand["type"],
    suffix: string,
    payload: LearningCommand["payload"],
    occurredAt: string,
    actor: LearningCommand["actor"] = {
      type: "learner",
      userId: scope.learnerId,
    },
  ): LearningCommand =>
    ({
      schemaVersion: LEARNING_EVENT_CONTRACT_VERSION,
      type,
      installationId: scope.installationId,
      learnerId: scope.learnerId,
      idempotencyKey: `${prefix}-${suffix}`,
      contentVersion: "conformance-1.0.0",
      occurredAt,
      actor,
      payload,
    }) as LearningCommand;

  const enrollment = command(
    "path.enroll",
    "enroll",
    {
      pathId: "conformance-path",
      pathTitle: "Learning-event adapter conformance",
      moduleIds: ["module-1", "module-2"],
      badge: {
        id: "conformance-badge",
        name: "Conformance",
        description: "Evidence generated by the adapter conformance harness.",
      },
    },
    "2026-07-28T12:00:00.000Z",
  );
  const firstEnrollment = await engine.execute(enrollment, learnerAccess);
  const replayedEnrollment = await engine.execute(enrollment, learnerAccess);
  expect(!firstEnrollment.replayed, "The first command was incorrectly replayed.");
  expect(replayedEnrollment.replayed, "An identical retry was not replayed.");
  expect(
    firstEnrollment.event.id === replayedEnrollment.event.id,
    "An identical retry created a second event.",
  );
  checks.push("idempotent-retry");

  await expectEngineError(
    () =>
      engine.execute(
        {
          ...enrollment,
          payload: { ...enrollment.payload, pathTitle: "Rebound title" },
        } as LearningCommand,
        learnerAccess,
      ),
    "idempotency-conflict",
  );
  checks.push("idempotency-rebinding-denied");

  const attemptOne = command(
    "assessment.record",
    "attempt-1",
    {
      attemptId: `${prefix}-attempt-1`,
      pathId: "conformance-path",
      moduleId: "module-1",
      assessmentVersion: "1.0.0",
      answers: { "question-1": 0, "question-2": null },
      scorePercent: 25,
      passed: false,
    },
    "2026-07-28T12:01:00.000Z",
  );
  const attemptTwo = command(
    "assessment.record",
    "attempt-2",
    {
      attemptId: `${prefix}-attempt-2`,
      pathId: "conformance-path",
      moduleId: "module-1",
      assessmentVersion: "1.0.0",
      answers: { "question-1": 1, "question-2": 0 },
      scorePercent: 100,
      passed: true,
    },
    "2026-07-28T12:02:00.000Z",
  );
  await Promise.all([
    engine.execute(attemptOne, learnerAccess),
    engine.execute(attemptTwo, learnerAccess),
  ]);
  const afterAttempts = await engine.rebuild(
    scope.installationId,
    scope.learnerId,
    learnerAccess,
  );
  expect(afterAttempts.attempts.length === 2, "A concurrent attempt was lost.");
  expect(
    afterAttempts.attempts.some(
      (attempt) =>
        attempt.originalScorePercent === 25 &&
        attempt.answers["question-1"] === 0 &&
        attempt.answers["question-2"] === null,
    ),
    "The original falsey assessment answers or score were not preserved.",
  );
  checks.push("concurrent-attempts", "immutable-original-attempt");

  await engine.execute(
    command(
      "assessment.correct",
      "correction-1",
      {
        correctionId: `${prefix}-correction-1`,
        attemptId: `${prefix}-attempt-1`,
        assessmentVersion: "1.0.0",
        scorePercent: 75,
        passed: true,
        reason: "Conformance correction preserves the original result.",
      },
      "2026-07-28T12:03:00.000Z",
      { type: "owner", userId: ownerId },
    ),
    ownerAccess,
  );
  for (const [index, moduleId] of ["module-1", "module-2"].entries()) {
    await engine.execute(
      command(
        "module.complete",
        `complete-${index + 1}`,
        {
          pathId: "conformance-path",
          moduleId,
          evidenceRefs: [`conformance:${moduleId}`],
        },
        `2026-07-28T12:0${index + 4}:00.000Z`,
      ),
      learnerAccess,
    );
  }

  const rebuilt = await engine.rebuild(
    scope.installationId,
    scope.learnerId,
    learnerAccess,
  );
  expect(rebuilt.revision === 6, "The rebuilt revision was not deterministic.");
  expect(rebuilt.badges.length === 1, "Badge evidence was not rebuilt.");
  expect(
    rebuilt.transcript[0]?.completionPercent === 100,
    "Transcript completion was not rebuilt.",
  );
  expect(
    rebuilt.attempts.find(
      (attempt) => attempt.attemptId === `${prefix}-attempt-1`,
    )?.originalScorePercent === 25,
    "A correction overwrote the original assessment score.",
  );
  expect(
    rebuilt.attempts.find(
      (attempt) => attempt.attemptId === `${prefix}-attempt-1`,
    )?.effectiveScorePercent === 75,
    "The appended correction was not projected.",
  );
  checks.push("deterministic-rebuild", "transcript-badge-correction");

  const importedProgress = {
    schemaVersion: 1 as const,
    displayName: "Conformance learner",
    startedPathIds: ["portable-path"],
    completedModuleIds: ["portable-module"],
    attempts: [],
    capstoneSubmissions: [],
    badges: [],
    updatedAt: "2026-07-28T12:06:00.000Z",
  };
  const progressImport = command(
    "progress.import",
    "progress-import",
    {
      source: "browser-local-v1",
      sourceChecksum:
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      synchronizedAt: "2026-07-28T12:06:00.000Z",
      progress: importedProgress,
    },
    "2026-07-28T12:06:00.000Z",
  );
  const firstImport = await engine.execute(progressImport, learnerAccess);
  const replayedImport = await engine.execute(progressImport, learnerAccess);
  expect(!firstImport.replayed, "The first progress import was incorrectly replayed.");
  expect(replayedImport.replayed, "An identical progress import was not replayed.");
  expect(
    JSON.stringify(replayedImport.projection.progressSnapshot) ===
      JSON.stringify(importedProgress),
    "The imported progress snapshot was not rebuilt exactly.",
  );
  expect(
    replayedImport.projection.enrollments.length === 0 &&
      replayedImport.projection.attempts.length === 0,
    "A progress import did not reset earlier granular projection state.",
  );
  checks.push("authoritative-progress-import");

  await expectEngineError(
    () =>
      engine.rebuild(scope.installationId, scope.learnerId, {
        ...learnerAccess,
        actorUserId: `${prefix}-other-learner`,
      }),
    "access-denied",
  );
  checks.push("authorization-isolation");

  const exported = await engine.export(
    scope.installationId,
    scope.learnerId,
    learnerAccess,
  );
  expect(
    JSON.stringify(exported) === JSON.stringify(await store.list(
      scope.installationId,
      scope.learnerId,
    )),
    "The event export was not lossless.",
  );
  checks.push("lossless-export");

  const deletedEventCount = await engine.delete(
    scope.installationId,
    scope.learnerId,
    learnerAccess,
  );
  expect(
    deletedEventCount === exported.length,
    "The deletion receipt count did not match the exported event count.",
  );
  expect(
    (await store.list(scope.installationId, scope.learnerId)).length === 0,
    "Deletion left authoritative learner events behind.",
  );
  checks.push("governed-deletion");

  return {
    contractVersion: LEARNING_EVENT_CONTRACT_VERSION,
    checks,
    eventCountBeforeDeletion: exported.length,
    deletedEventCount,
  };
}

function expect(condition: boolean, message: string): asserts condition {
  if (!condition) throw new Error(`Learning-event conformance failed: ${message}`);
}

async function expectEngineError(
  action: () => Promise<unknown>,
  code: LearningEventEngineError["code"],
): Promise<void> {
  try {
    await action();
  } catch (error) {
    if (error instanceof LearningEventEngineError && error.code === code) {
      return;
    }
    throw error;
  }
  throw new Error(
    `Learning-event conformance failed: expected engine error ${code}.`,
  );
}
